version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:5000"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
